[workspace]
resolver = "2"
members = [
    "psp-ml",
    "cargo-psp-ml",
    "audio-recorder",
    "examples/mnist-bench",
    "examples/hello-psp",
    "psp-runner",
]
default-members = [
    "psp-ml",
    "examples/mnist-bench",
]